#ifndef _I386_MULTIBOOT_H
#define _I386_MULTIBOOT_H 1

#define MULTIBOOT_HEADER_MAGIC              0xe85250d6
#define MULTIBOOT_HEADER_ARCHITECTURE_I386  0

#define MULTIBOOT_HEADER_TAG_END_TYPE       0
#define MULTIBOOT_HEADER_TAG_END_SIZE       8


#endif