#define MULTIBOOT_HEADER_MAGIC                  0xE85250D6
#define MULTIBOOT_HEADER_ARCHITECTURE_I386      0
#define HEADER_LENGTH(from, to)                 (to - from)
#define CHECKSUM(magic, arch, length)           -(magic + arch + length)

#define MULTIBOOT_HEADER_ALIGN                  8

#define MULTIBOOT_TAG_TYPE_MMAP              6

#define MULTIBOOT_HEADER_TAG_END  0
#define MULTIBOOT_HEADER_TAG_INFORMATION_REQUEST  1
#define MULTIBOOT_HEADER_TAG_ADDRESS  2
#define MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS  3
#define MULTIBOOT_HEADER_TAG_CONSOLE_FLAGS  4
#define MULTIBOOT_HEADER_TAG_FRAMEBUFFER  5
#define MULTIBOOT_HEADER_TAG_MODULE_ALIGN  6
#define MULTIBOOT_HEADER_TAG_EFI_BS        7
#define MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS_EFI32  8
#define MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS_EFI64  9
#define MULTIBOOT_HEADER_TAG_RELOCATABLE  10

#define MULTIBOOT_HEADER_TAG_OPTIONAL 1
